# yaml-language-server: $schema=https://raw.githubusercontent.com/renderinc/render-yaml-schema/master/render.schema.json
services:
  - type: web
    name: fueltrack-backend
    env: docker
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d1lgtdp5pdvs73bvg2cg-a.oregon-postgres.render.com;Port=5432;Database=fueltrack_db_frnm;Username=fueltrack_db_frnm_user;Password=zVKJHFHvgIE7sAlBUMlhFvlNN5rTqrXZ;SSL Mode=Require;Trust Server Certificate=true;Timeout=30;Command Timeout=60