# yaml-language-server: $schema=https://raw.githubusercontent.com/renderinc/render-yaml-schema/master/render.schema.json
services:
  - type: web
    name: fueltrack-backend
    env: docker
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d2qikul6ubrc73de4lig-a;Port=5432;Database=fueltrack_db_7izl;Username=fueltrack_user;Password=JpgkS3DdQtjjlE41gofz1EUE4cb9Ks2p;SslMode=Require;TrustServerCertificate=true;Timeout=30;CommandTimeout=60